### ISSUE TITLE
New generation of `modules/` overwrite module reference overview

### ISSUE THREAD

**Issue by stuartromanek** [apostrophecms/apostrophe-documentation#140]
The leading link in the Modules heading of SUMMARY.md should go to an overview of the module reference .. that file keeps being overwritten by the generation

original file we want is here https://raw.githubusercontent.com/apostrophecms/apostrophe-documentation/legacy-final/modules/index.md

should be named `README.md`

**Comment by boutell** [comment]
Took the liberty of fixing this in master.

The `generate` script does clear out `/modules`, which I kept, but I added a command to copy `_tip-ins/modules.md`, which sure enough already existed for this reason. I think logic for it used to be in the documentation generator and got removed in my changes last week, but it's simple and clear to have it in `generate` instead.
