### ISSUE TITLE
Broken links into the documentation

### ISSUE THREAD

**Issue by Jose96GIT** [apostrophecms/apostrophe-documentation#141]
Hi, I've found some broken links into the documentation like the links of this part of the documentation.

https://docs.apostrophecms.org/apostrophe/tutorials/intermediate/forms#displaying-and-submitting-the-form-contact-form-widgets

**Comment by johnspackman** [comment]
It looks like any page which has links outside the page are broken, eg this page has the same issue:

https://docs.apostrophecms.org/apostrophe/tutorials/howtos/ckeditor

**Comment by abea** [comment]
These links seem all fixed at this point. Thanks for the reports.
