### ISSUE TITLE
Forms article is orphaned by the table of contents, needs to be broken up

### ISSUE THREAD

**Issue by boutell** [apostrophecms/apostrophe-documentation#187]
This article:

./tutorials/advanced-development/forms.md

Is problematic because as written it has to start with two big disclaimers about two different alternatives that almost certainly cover the use case just fine without writing any code.

And yet, the material in here is critical for people who want to understand:

* How to add forms to an Apostrophe site in the general case (you should use apostrophe-forms)
* How to add a form for submitting a specific piece type directly to Apostrophe's database, like contributing an article (you should use apostrophe-pieces-submit-widgets)
* How to create your own AJAX form submissions in a way that is compatible with Apostrophe's CSRF protection (use jQuery's functions for AJAX, or use the apos.utils.post function, either will do it for you)

... And I think that might be enough? The longer part where we talk about how to recreate something like apostrophe-pieces-submit-widgets is probably not that interesting anymore.

cc @abea, let me know if you disagree about ditching that main component of the old article

**Comment by abea** [comment]
I think you're right that the last "Going deeper with Apostrophe: creating a contact-form module" section is no longer necessary. People can dig into apostrophe-submit-widgets themselves if needed. Ultimately the docs should be pointing people in the right direction for solving problems, which that isn't for this problem.

That is a well written guide. It would be nice to have as a blog post or something, but at this point would seem odd to post with the other options available.
