### ISSUE TITLE
how-to-send-email article is 404'ing

### ISSUE THREAD

**Issue by boutell** [apostrophecms/apostrophe-documentation#190]
The link in google is:

https://docs.apostrophecms.org/apostrophe/tutorials/howtos/email

Is this a busted redirect?

**Comment by stephenkostas** [comment]
Looks like the .md file is in the wrong place. Fixing now...

**Comment by boutell** [comment]
I fixed this.

**Comment by boutell** [comment]
The redirect I put in isn't being honored so far for some reason. Possibly those are just slower than other content updates?

**Comment by boutell** [comment]
The redirect works now.

**Comment by boutell** [comment]
I missed that you had also done this, pardon.
