### ISSUE TITLE
Use npm scripts for commands

### ISSUE THREAD

**Issue by alexgleason** [apostrophecms/apostrophe-documentation#23]
I think it would make sense to have something like `npm run generate` instead of using a bash script.

Also, adding a package.json with habit as a dependency might make this easier to build.

**Comment by boutell** [comment]
Even if it just runs the bash scripts out of a folder, it's still a pretty good idea.

It could also run habit from that dependency rather than as a global, yes.

**Comment by stephenkostas** [comment]
This seems to be a very very stale ticket. Should we close it?

**Comment by abea** [comment]
Yeahs, since we're now using Gitbook this isn't relevant anymore.
