### ISSUE TITLE
[DOCS ISSUE] Page: Custom columns and sortable columns for the "manage" modal

### ISSUE THREAD

**Issue by adamhowse** [apostrophecms/apostrophe-documentation#278]
Following the example results in the application crashing to the console with this error:

> ReferenceError: self is not defined

Caused by:

`return self.partial('manageUpdatedAt.html', { value: value });`

I can however get it working by wrapping it in this, which is not consistent with how it should work according to the docs:

```
  beforeConstruct: function(self, options) {
    options.addColumns = [
      {
        name: 'updatedAt',
        label: 'Last Updated',
        sort: {
          updatedAt: 1
        },
        partial: function(value) {
          if (!value) {
            return '';
          }
          return self.partial('manageUpdatedAt.html', { value: value });
        }
      }
    ].concat(options.addColumns || [])
  }
```

**Comment by boutell** [comment]
Correct, you can't use the partial technique in plain old addFields because it has no access to self, this needs addressing in the docs. In 3.0 this issue will go away for... well, several reasons, including a completely new admin UI... but also because `self` can be made available when configuring fields without as much work.

**Comment by abea** [comment]
Where in the docs is the confusion coming from?

**Comment by adamhowse** [comment]
It's coming from this page (following the example code will result in the error, unless using the fix I posted above): https://docs.apostrophecms.org/advanced-topics/advanced-pieces-topics/adding-columns.html

**Comment by abea** [comment]
I'll put it on my list, but if you would be willing to submit a PR to the docs we'd really appreciate it.
