### ISSUE TITLE
[DOCS ISSUE] Page: HOWTOs

### ISSUE THREAD

**Issue by southernsons** [apostrophecms/apostrophe-documentation#281]
Hello there,

Kinda new to this.

How can I move the site from one server to another server? Is there a proper step by step by step guide?

**Comment by abea** [comment]
Hello there. I think I answered this in StackOverflow as well. That's not currently a guide that's written.

**Comment by abea** [comment]
Did you have any particular questions about that response?

**Comment by southernsons** [comment]
@abea thank you for your response. Yes I did ask on Stack as well but I was hoping to get a more detailed answer here. But I assume not. I need to move 3 sites from AWS to a customer's custom VPS (we did not build the sites but the customer is unhappy with the current service provider and asked my company to assist him). Since we have never done an Apostrophe Migration I was hoping to have some sort of indepth tutorial (or even video) :-)

**Comment by abea** [comment]
Nothing like that yet. The key thing is to get the server set up property. There are a few detailed guides for that part: https://docs.apostrophecms.org/devops/deployment/.

Then it really is a matter of migrating the MongoDB database, which is a relatively simple export/import process, and deploying the codebase, and the media assets. If there are any cron jobs on the old server that'd be something to manually move as well.

The rest shouldn't be any different for a migration, so the deployment guides should cover it. Nginx configuration is not specific to Apostrophe, though `mechanic` makes that a lot easier. Of course, I would do a test run to get it working on a temporary domain/subdomain to make sure.
