### ISSUE TITLE
[DOCS ISSUE] Page: Building Navigation

### ISSUE THREAD

**Issue by einargustafsson** [apostrophecms/apostrophe-documentation#312]
just a small minute spelling error but hitting close to my viking home :) There is a d missing in the word Yggdrasill - and technically should be with two l's

**Comment by abea** [comment]
Let the debate begin over one or two Ls!

Just kidding. The executive decision has been made to go Old Norse. And maybe translate all the docs into Old Norse while we're at it.

All kidding aside, thank you for this correction, Einar! We clearly swung too hard using this example without confirming the spelling.

**Comment by abea** [comment]
I'm honestly now paralyzed with indecision about the Ls issue, actually.

**Comment by einargustafsson** [comment]
The one or two l's bother me very little in comparison with the missing d. :)

Einar Þór Gústafsson
Co-founder, head of product & business development

Office: +354 888 0020
Mobile: +354 858 1884
Email: einar@getlocl.com
Ecommerce and CMS solution for Travel https://getlocl.com ( https://getlocl.com/ )

( https://www.getlocal.is )
