### ISSUE TITLE
[DOCS ISSUE] Page: AJAX Features: Enhanced Browsing for Pieces

### ISSUE THREAD

**Issue by hexitex** [apostrophecms/apostrophe-documentation#331]
Code sample for infinite scroll should be 

 `<a data-apos-ajax-infinite-scroll href="{{ data.url | build({ page: data.currentPage + 1, append: 1 })}}"></a>`
not
 `<a data-apos-ajax-infinite-scroll href="{{ data.url}} | build({ page: data.currentPage + 1, append: 1 })"></a>`

**Comment by boutell** [comment]
Fixed, thanks.
