### ISSUE TITLE
Remove .html from URLs

### ISSUE THREAD

**Issue by alexgleason** [apostrophecms/apostrophe-documentation#36]
This can be done through most server config and makes for prettier URLs.

Nginx: http://serverfault.com/questions/346994/hide-html-file-extensions-using-nginx-rewrites#346999
Apache: http://stackoverflow.com/questions/1992183/how-to-hide-the-html-extension-with-apache-mod-rewrite#1992191

Not totally related: I love that Harp does this by default. If we can find some magic between Harp and Habit you'd ideally be able to run the Habit server and it would just ignore your .html extensions.

**Comment by abea** [comment]
Resolved with the move to Gitbook.
