### ISSUE TITLE
How to add pieces to mongodb collection or filter pieces?

### ISSUE THREAD

**Issue by andrewbenrichard** [apostrophecms/apostrophe-documentation#378]
I want to manipulate pieces but can't find them in my MongoDB collection, how do I do that please

**Comment by abea** [comment]
What have you tried so far? How are you trying to manipulate pieces in the database? Often that can lead to problems if something is changed that Apostrophe needs.

**Comment by andrewbenrichard** [comment]
For now, I can't find pieces I added from the site on MongoDB. 
 There are ways to do it safely, though.

> There are ways to do it safely, though.

Please what are the recommended methods of doing this

**Comment by abea** [comment]
The pieces are all in the `aposDocs` collection. You can find them by their `type` property. So if it's an `article` piece type, you could use the `{ type: 'article'}` query.

I still don't know if you are trying to do this from server side code or from the MongoDB CLI, for one thing. This is a good place to start finding more information: https://v2.docs.apostrophecms.org/advanced-topics/database/accessing-the-database-directly.html
